ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -h /home/alpine -D alpine \
    && addgroup pulse \
    && apk add --no-cache --purge -uU \
        curl icu-libs unzip zlib-dev musl \
        alsa-utils \
        mesa-gl mesa-dri-swrast \
        pulseaudio udev \
	ffmpeg-libs \
        libstdc++ libgcc dbus-x11 \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk add --no-cache --purge -u \
        alsa-plugins-pulse \
        firefox \
    && adduser alpine audio \
    && adduser alpine video \
    && adduser alpine pulse \
    && rm -rf /var/cache/apk/* /tmp/*
#
VOLUME /home/alpine/
#
USER alpine
WORKDIR /home/alpine/
#
ENTRYPOINT ["/usr/bin/firefox"]
# ENTRYPOINT ["/bin/bash"]
# ENTRYPOINT ["/init"]
