#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0  ]; then echo "[$0] $@"; fi; }

if [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Add ${S6_USER:-alpine} to groups: audio, pulse, video";
    if [ -n "${GID_AUDIO}" ]; # update gid of 'audio' if defined
    then groupmod -o -g "${GID_AUDIO}" audio;
    fi;
    adduser ${S6_USER:-alpine} audio;
    if [ -n "${GID_PULSE}" ]; # update gid of 'pulse' if defined
    then groupmod -o -g "${GID_PULSE}" pulse;
    fi;
    adduser ${S6_USER:-alpine} pulse;
    if [ -n "${GID_VIDEO}" ]; # update gid of 'video' if defined
    then groupmod -o -g "${GID_VIDEO}" video;
    fi;
    adduser ${S6_USER:-alpine} video;
fi;

S6_USERHOME="${S6_USERHOME:-$(getent passwd ${S6_USER:-alpine} | cut -d: -f6)}";
USERHOMEDIR="${HOME:-$S6_USERHOME}";

# ensure firefox dirs
vecho "Ensure configuration directories exist.";
mkdir -p \
    "${USERHOMEDIR}/Downloads" \
    "${USERHOMEDIR}/.local" \
    "${USERHOMEDIR}/.mozilla" \
    ;

# fix permissions
if [ -z "${FIREFOX_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown ${S6_USER:-alpine}:${PGID:-1000} \
        "${USERHOMEDIR}" \
        "${USERHOMEDIR}/Downloads" \
        ;

    find "${USERHOMEDIR}/.mozilla" "${USERHOMEDIR}/.local" \
        \! -user ${S6_USER:-alpine} -exec \
        chown --no-dereference \
        ${S6_USER:-alpine}:${PGID:-1000} \
        '{}' +;
fi;

# may become cumbersome if DOWNLOADS has large number of files
if [ -n "${FIREFOX_PERMFIX_DOWNLOADDIR}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions on ${USERHOMEDIR}/Downloads files.";
    find "${USERHOMEDIR}/Downloads" \
        \! -user ${S6_USER:-alpine} -exec \
        chown --no-dereference \
        ${S6_USER:-alpine}:${PGID:-1000} \
        '{}' +;
fi;
